import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import Footer from "./statics/Footer";
import Header from "./statics/Header";
import ConvexClientProvider from "./ConvexClientProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

const inter = Montserrat({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Front Ender AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen dark",
          inter.className
        )}
      >
        <ConvexClientProvider>
          <Toaster  />
          <Header />
          {children}
          <Footer />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
